services:

  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: eureka-server

networks:
  default:
    external: true
    name: microservices-net