server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:eureka-server}:${SERVER_PORT:8761}/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
